# This file contains the fastlane.tools configuration
# Documentation: https://docs.fastlane.tools
# Actions:       https://docs.fastlane.tools/actions
# Plugins:       https://docs.fastlane.tools/plugins/available-plugins

# Uncomment to auto-update fastlane
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload UAT APK"
  lane :uat do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    gradle(
      task: "assemble",
      build_type: "Release",
      flavor: "uat",
      print_command: true
    )

    release_notes = UI.input("Enter the release notes:")

    # Integrate Firebase App Distribution, Play Store, or internal tools here
    # firebase_app_distribution or upload_to_play_store etc.
    firebase_app_distribution(
      app: "1:217803854766:android:5ea8f30c972ee95a48ee3f",
      groups: "internal_tester",
      release_notes: release_notes,
      android_artifact_type: "APK",
      service_credentials_file: "../android/app/src/uat/firebase-service.json",
      apk_path: "../android/app/build/outputs/apk/uat/release/app-uat-release.apk",
    )
  end

  desc "Build and upload PROD APK"
  lane :prod do
    increment_version_code(
      gradle_file_path: "app/build.gradle"
    )

    gradle(
      task: "assemble",
      build_type: "Release",
      flavor: "prod",
      print_command: true
    )

    release_notes = UI.input("Enter the release notes:")

    # Integrate Firebase App Distribution, Play Store, or internal tools here
    # firebase_app_distribution or upload_to_play_store etc.
    firebase_app_distribution(
      app: "1:217803854766:android:dfc9b5288104105448ee3f",
      groups: "internal_tester",
      release_notes: release_notes,
      android_artifact_type: "APK",
      service_credentials_file: "../android/app/src/prod/firebase-service.json",
      apk_path: "../android/app/build/outputs/apk/prod/release/app-prod-release.apk",
    )
  end
end
